name: Check pull requests for conflicts

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  conflibot:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
      checks: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: wktk/conflibot@4881912dc3fe459059127d667251d5b324622299 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exclude: ""
